-- SELECT
    SELECT * FROM VTABLE
    SELECT VCOLUMN1, VCOLUMN2 FROM VTABLE
    SELECT a.VCOLUMN1, b.VCOLUMN2 FROM VTABLE1 AS a, VTABLE2 AS b
    SELECT VCOLUMN AS RESULTCOLUMN1, VCOLUMN2 AS "Result Column 2" FROM VTABLE -- sETS THE COLUMN NAME
    SELECT DISTINCT VCOLUMN1, VCOLUMN2 FROM VTABLE -- REMOVE DUPLICATES
    SELECT * FROM VTABLE LIMIT 3
    -- FUNCTIONS
        SELECT COUNT(DISTINCT VCOLUMN1) FROM VTABLE -- RETURNS THE COUNT
        SELECT MIN(VCOLUMN) FROM VTABLE -- MAX()
        SELECT AVG(VCOLUMN) FROM VTABLE
        SELECT SUM(VCOLUMN) FROM VTABLE
        SELECT CONCAT_WS(', ', VCOLUMN1, VCOLUMN2, VCOLUMN3, VCOLUMN4) AS RESULTCOLUMN FROM VTABLE;
    -- WHERE
        SELECT * FROM TABLE WHERE VCOLUMN1 <> 'STRING' -- NOT EQUAL; CAN ALSO > < => <= =
        SELECT * FROM TABLE WHERE VCOLUMN1 BETWEEN '1996-07-01' AND '1996-07-31' -- NOT BETWEEN, CAN ALSO 1 AND 10
        SELECT * FROM TABLE WHERE VCOLUMN LIKE '_ELLO%' -- HELLO WORLD
        SELECT * FROM TABLE WHERE VCOLUMN IN ('STRING1', 'STRING2', SELECT VCOLUMN FROM VTABLE) -- LIKE 'OR'
        SELECT * FROM TABLE WHERE VCOLUMN = 1 AND VCOLUMN2 = 1 OR (VCOLUMN3 = 1 AND NOT VCOLUMN4 = 1) -- OR NOT () AND
        SELECT * FROM TABLE WHERE VCOLUMN IS NULL -- IS NOT NULL
        SELECT * FROM VTABLE1 AS a, VTABLE2 AS b WHERE a.VCOLUMN1 = b.COLUMN2
    -- ORDER
        SELECT * FROM VTABLE ORDER BY VCOLUMN1
        SELECT * FROM VTABLE ORDER BY VCOLUMN1, VCOLUMN2 ASC -- ORDER BY VCOLUMN1, IF SAME ORDER BY VCOLUMN2
        SELECT * FROM VTABLE ORDER BY VCOLUMN1 ASC, VCOLUMN2 DESC -- ORDER BY VCOLUMN1, IF SAME ORDER BY VCOLUMN2 DESC
-- INSERT INTO
    INSERT INTO VTABLE (VCOLUMN1, VCOLUMN2) VALUES (VALUE1, VALUE2)
    INSERT INTO VTABLE VALUES (VALUE1, VALUE2) -- CONSECUTIVE COLUMNS
-- UPDATE
    UPDATE VTABLE SET VCOLUMN1 = 1, VCOLUMN2 = 2 WHERE VCOLUMN3 = 1
-- DELETE
    DELETE FROM VTABLE -- DELETE ALL RECORDS
    DELETE FROM VTABLE WHERE VCOLUMN = 1
-- JOIN
    SELECT a.VCOLUMN1, b.VCOLUMN2 FROM VTABLE1 AS a INNER JOIN VTABLE2 AS b ON a.VCOLUMN1 = b.VCOLUMN2; -- WITH A AND B
    SELECT a.VCOLUMN1, b.VCOLUMN2 FROM VTABLE1 AS a RIGHT JOIN VTABLE2 AS b ON a.VCOLUMN1 = b.VCOLUMN2; -- ALL B
    SELECT a.VCOLUMN1, b.VCOLUMN2 FROM VTABLE1 AS a LEFT JOIN VTABLE2 AS b ON a.VCOLUMN1 = b.VCOLUMN2; -- ALL A
    SELECT a.VCOLUMN1, b.VCOLUMN2 FROM VTABLE1 AS a CROSS JOIN VTABLE2 AS b ON a.VCOLUMN1 = b.VCOLUMN2; -- ALL VALUES




UPDATE
DELETE
INSERT INTO
CREATE DATABASE
ALTER DATABASE
CREATE TABLE
ALTER TABLE
DROP TABLE
CREATE INDEX
DROP INDEX