CREATE TABLE IF NOT EXISTS OFFICERS
(
OFFICER_ID INT AUTO_INCREMENT PRIMARY KEY,
FIRSTNAME VARCHAR(255),
MIDDLEINITIAL VARCHAR(255),
LASTNAME VARCHAR(255),
DESCRIPTION VARCHAR(255),
POSITION VARCHAR(255),
STRAND VARCHAR(255),
USER_ID INT,
FOREIGN KEY (USER_ID) REFERENCES USERS(USERS) ON DELETE CASCADE,
UPDATETIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP);